version: "3.7"
services:
  containerizor:
    depends_on: 
      - db
    image: asankov/containerizor:1.5
    ports:
      - "4000:4000"
    environment:
      DB_HOST: 'db'
      DB_PORT: 5432
      DB_USER: 'admin'
      DB_PASS: 'password'
      DB_NAME: 'containerizor'
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'containerizor'
      POSTGRES_HOST_AUTH_METHOD: 'password'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: